---
title: "Figure ratio ABI:NPP vs water balance"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
--- 

## Prepare Data 

```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```


```{r, message=FALSE}
library(tidyverse)
library(sf)
library(SPEI)
library(ggh4x)
library(geomtextpath)
library(metR)
library(ggsci)
library(patchwork)
library(fields)
library(splines)
source("scripts/aux.R")
```

```{r}
annual_pet <- read_csv("data/dendroadaptamed_spei_climate.csv") |> 
  dplyr::select(sp_elev, year, monthly_pet, monthly_tmed, monthly_prec) |> 
  group_by(sp_elev, year) |>
  summarise(pet = sum(monthly_pet), 
            prec = sum(monthly_prec),
            tmed = mean(monthly_tmed, na.rm = TRUE)) |> 
  rowwise() |> 
  mutate(water_balance = prec - pet)
```


```{r}
ratio <- read_csv("data/dendroadaptamed_ratio_abinpp.csv") |> 
  dplyr::select(year, sp_code, elev_code, sp_elev, ratio_abi_npp = ratio) 

df <- ratio |> 
  inner_join(annual_pet) |> 
  pivot_longer(pet:water_balance, values_to = "mean_climate", 
               names_to = "climate_variable")
```



```{r}
label_npp <- "Annual~NPP[MODIS]~(g~C~m^2~year^{-1})"
label_ratio <- "ABI:NPP"
label_wb <- "P-PET (mm)"
```



```{r}
## Scales 
y_scales <- list(
  scale_y_continuous(limits = c(0, 0.5)),
  scale_y_continuous(limits = c(0,1250)),
  scale_y_continuous(limits = c(0, 700))
)
```


## Water-Balance 
```{r, fig.width=12, fig.height=6}
plot_wb <- 
  df |> 
  filter(climate_variable == "water_balance") |>
  ggplot(aes(x=mean_climate, y = ratio_abi_npp, colour = sp_code)) + 
  geom_point(aes(shape = elev_code, fill = sp_code), alpha = .5) +
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") + 
  theme_bw() + 
  geom_smooth(method = "lm", se = FALSE, linewidth = .8) +
  geom_smooth(aes(), 
              method = "nls", 
              formula=y~SSlogis(x, Asym, xmid, scal),
              se =  FALSE, # this is important 
              linewidth = 1, colour = "black") + 
  xlab("Water balance (mm)")+
  theme(
    panel.grid = element_blank(), 
    strip.background = element_blank(),
    strip.placement = "outside",
    legend.position = "top", 
    strip.text = element_text(face = "bold", size = 14)
  ) + 
  scale_x_continuous(limits = c(-900, 1200)) + 
  ylab(label_ratio)


# Mira esto para inspirarte y crear IC en las estimaciones de los modelos 
# https://derekogle.com/fishR/examples/oldFishRVignettes/VonBertalanffy.pdf
plot_wb
```


## Tmed
```{r, fig.width=12, fig.height=6}
plot_tmed <- 
  df |>
  filter(climate_variable == "tmed") |> 
  ggplot(aes(x=mean_climate, y = ratio_abi_npp, colour = sp_code)) + 
  geom_point(aes(shape = elev_code, fill = sp_code), alpha = .5) +
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") + 
  theme_bw() +
  geom_smooth(method = "lm", se = FALSE, size = .8) +
  geom_smooth(aes(),
              method = "nls", 
              formula = y ~ SSasymp(x, Asym, R0, lrc),
                #               SSlogis(x, Asym, xmid, scal),
              se =  FALSE, # this is important 
              linewidth = 1, colour = "black") +
  ylab(label_ratio) + 
  xlab("Annual Mean Temperature (ºC)") +
  theme(
    panel.grid = element_blank(), 
    strip.background = element_blank(),
    strip.placement = "outside",
    legend.position = "none", 
    strip.text = element_text(face = "bold", size = 14)) +
  scale_x_continuous(limits = c(7.5, 17.5)) 

plot_tmed
```




```{r}
install.packages("univariateML")
library(univariateML)

d <- dtmed

hist(d$tmed)

AIC(
  mlbetapr(d$tmed),
  mlexp(d$tmed),
  mlinvgamma(d$tmed),
  mlgamma(d$tmed),
  mllnorm(d$tmed),
  mlrayleigh(d$tmed),
  mlinvgauss(d$tmed),
  mlweibull(d$tmed),
  mlinvweibull(d$tmed),
  mllgamma(d$tmed)
) |> arrange(AIC)


mllnorm(d$tmed)

```



```{r}
library(segmented)

model <- lm(rat ~ tmed, data = dtmed)
segmented_model <- segmented(model, seg.Z = ~tmed)


seg_preds <- predict(segmented_model)
dtmed$seg_res <-  dtmed$rat- seg_preds

# Plot the original data with the fitted model
plot(
  dtmed$tmed, dtmed$rat,
  main = "Piecewise Regression Fit",
  xlab = "Independent Variable (x)",
  ylab = "Dependent Variable (y)",
  col = "blue"
)
lines(dtmed$tmed, seg_preds,col = "red", lwd = 2)
```




```{r}
# Define the maximum ratio
MR <- 0.6

# Define the nonlinear model function
model_formula <- rat ~ MR * exp(-0.5 * ((tmed - t) / b)^a)


# Generate sequences of start values
t_values <- seq(6, 15, by = 0.5)
b_values <- seq(-2, 2, by = 0.1)
a_values <- seq(-2, 2, by = 0.1)

start_grid <- expand.grid(t = t_values, b = b_values, a = a_values)

# Create a grid of starting values
# Function to fit the model
fit_model <- function(start) {
  tryCatch({
    nls(model_formula, data = dtmed, start = as.list(start))
  }, error = function(e) NULL)
}

# Fit the model using the grid of starting values
fits <- apply(start_grid, 1, fit_model)

# Filter out unsuccessful fits
successful_fits <- Filter(Negate(is.null), fits)

# Check if any model was successfully fitted
if (length(successful_fits) > 0) {
  # Get the best fit (using the first successful fit in this case)
  best_fit <- successful_fits[[1]]

  # Print the summary of the model fit
  summary(best_fit)

  # Predict values
  dtmed$rat_pred <- predict(best_fit)

  # Plot the original data and fitted values
  ggplot(dtmed, aes(x = tmed, y = rat)) +
    geom_point() +
    geom_line(aes(y = rat_pred), color = 'red') +
    theme_minimal() +
    labs(title = "Fitted Nonlinear Model using nls", x = "tmed", y = "rat")
} else {
  message("Model fitting failed with all starting values.")
}



```





```{r}
### Otros lios 
dtmed <- df |> filter(climate_variable == "tmed") |> dplyr::select(rat = ratio_abi_npp, tmed = mean_climate)

write_csv(dtmed, "/Users/ajpelu/Desktop/dtmed.csv")
# rat ~ max(rat) * g2 + ej 

# g2 = exp(-0.5*((tmed - t)/b)^a) 

aux_max <- dtmed |> slice_max(rat)


# 
# rat ~ 0.626*(exp(-0.5*((tmed - 10.4)/b)^a)) 
# 
# g <- nls(dtmed$rat ~ c*exp(-0.5*(log(dtmed$tmed/a) / b)^2), data = dtmed, start = list(a = 10, b =1.5, c = 0.6))







model <- nls(rat ~ c * dlnorm(tmed, meanlog, sdlog),
             data = dtmed, 
             start = list(c = .6, meanlog = 2.4, sdlog = 0.1),
             control = nls.control(minFactor = 1/1000096,
                                   maxiter=10000))


plot(log(dtmed$rat) ~ dtmed$tmed)
# compute log 
dtmed$lograt <- log(dtmed$rat)

fit <- nls(lograt ~ b * tmed, data = dtmed, start = list(b = 0.1))

a <- coef(model)['a']
b <- coef(model)['b']


# Predict in log scale
dtmed$log_rat_pred <- predict(fit)

# Convert predictions back to original scale
dtmed$rat_pred <- exp(dtmed$log_rat_pred)


newdata <- data.frame(tmed = seq(0, 20, by = 0.5)) 
newdata$log_rat_pred <- predict(fit, newdata = newdata)
# Convert predictions back to original scale
newdata$rat_pred <- exp(newdata$log_rat_pred)


ggplot(dtmed, aes(x = tmed, y = rat)) +
  geom_point() +
  geom_line(data = newdata, aes(y = rat_pred), color = 'red') +
  theme_minimal() +
  labs(title = "Fitted Log-Normal NLS Model", x = "tmed", y = "rat")



g <- nls(rat ~ a * dlnorm(tmed, mean, sd), data =dtmed, 
         start = list(mean = 10, sd = 1.5, a = 0.62), algorithm = "plinear")



0.626*(exp(-0.5*((10 - 10.4)/-2)^.5))


temp.effect <- exp(-0.5*((tmed - tempX0)/tempXb)^2)

gm <- nls(rat ~ a* tmed^b, data = dtmed, start = list(a = 2000, b = -4), alg = "plinear")
summary(gm)

fit_function <- function(tmed) {
  a <- coef(gm)["a"]
  b <- coef(gm)["b"]
  return(a * tmed^b)
}

# Plot the data and the fitted curve
ggplot(dtmed, aes(x = tmed, y = rat)) +
  geom_point() +
  stat_function(fun = fit_function, color = "blue", size = 1) +
  labs(title = "Gamma NLS Fit",
       x = "Temperature (tmed)",
       y = "Ratios (rat)") +
  theme_minimal()


```




```{r}
# Define a self-starter function for a lognormal model
# Define the lognormal self-starter function
lognormal_start <- function(mCall, LHS, data, ...) {
  xy <- sortedXyData(mCall[["x"]], LHS, data)
  x <- xy$x
  y <- xy$y
  lm_fit <- lm(log(y) ~ x)
  a <- exp(coef(lm_fit)[1])
  b <- coef(lm_fit)[2]
  setNames(c(a, b), mCall[c("a", "b")])
}

# Define the lognormal model with self-starter
lognormal_model <- selfStart(~ a * exp(b * x), initial = lognormal_start, parameters = c("a", "b"))

# Fit the model using nls with the self-starter
nls_model <- nls(ratio_abi_npp ~ lognormal_model(mean_climate, a, b), data = df)

df$predicted <- predict(nls_model, newdata = df)


df |>
  filter(climate_variable == "tmed") |> 
  ggplot(aes(x=mean_climate, y = ratio_abi_npp, colour = sp_code)) + 
  geom_point(aes(shape = elev_code, fill = sp_code), alpha = .5) +
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") + 
  theme_bw() +
  geom_smooth(method = "lm", se = FALSE, size = .8) +
  geom_smooth(aes(),
              method = "nls", 
              formula = y ~ SSasymp(x, Asym, R0, lrc),
                #               SSlogis(x, Asym, xmid, scal),
              se =  FALSE, # this is important 
              linewidth = 1, colour = "black") +
  ylab(label_ratio) + 
  xlab("Annual Mean Temperature (ºC)") +
  theme(
    panel.grid = element_blank(), 
    strip.background = element_blank(),
    strip.placement = "outside",
    legend.position = "none", 
    strip.text = element_text(face = "bold", size = 14)) +
  scale_x_continuous(limits = c(7.5, 17.5)) 





```



```{r, eval=FALSE}
# black: logis 
# blue: asymp 

## evi 
t_evi <- df_plot |> filter(climate_variable == "tmed") |> 
  filter(y_variable == "evi_landsat") 

init_aysmp_evi <- as.data.frame(t(getInitial(mean_y ~ SSasymp(mean_climate, Asym, R0, lrc), data = t_evi)))
init_logis_evi <- as.data.frame(t(getInitial(mean_y ~ SSlogis(mean_climate, Asym, xmid, scal), data = t_evi)))


## npp
# asymp da error en NPP 
t_npp <- df_plot |> filter(climate_variable == "tmed") |> 
  filter(y_variable == "npp") 

# init_aysmp_npp <- as.data.frame(t(getInitial(mean_y ~ SSasymp(mean_climate, Asym, R0, lrc), data = wb_npp)))

init_logis_npp <- as.data.frame(t(getInitial(mean_y ~ SSlogis(mean_climate, Asym, xmid, scal), data = t_npp)))

## abi
t_abi <- df_plot |> filter(climate_variable == "tmed") |> 
  filter(y_variable == "abi") 
init_logis_abi <- as.data.frame(t(getInitial(mean_y ~ SSlogis(mean_climate, Asym, xmid, scal), data = t_abi)))

init_aysmp_abi <- as.data.frame(t(getInitial(mean_y ~ SSasymp(mean_climate, Asym, R0, lrc), data = t_abi)))
```


```{r, fig.width=12, fig.height=12}
f <- plot_wb / plot_tmed
f
ggsave(
  f, 
  file = "output/combined_fig.png",
  dpi = 300,
  width = 12, height = 8
)
```


## Surfaces
### Natural splines  
```{r, fig.width=12, fig.height=6}
# Using natural splines 

df_surfaces <- df_plot |>
  filter(climate_variable %in% c("water_balance", "tmed")) |> 
  filter(y_variable != "evi_modis") |> 
  mutate(climate_variable = fct_relevel(climate_variable, "water_balance","tmed")) |> 
  mutate(y_variable = fct_relevel(y_variable, "evi_landsat", "npp", "abi")) |> 
  pivot_wider(names_from = climate_variable, values_from = mean_climate) 


generate_predict <- function(data, v) { 
  
  surf <- data |> filter(y_variable == v)
  grid <- expand.grid(water_balance = seq(min(data$water_balance), 
                                        max(data$water_balance), 20), 
                    tmed = seq(min(data$tmed), 
                               max(data$tmed), 0.1))
  grid[[v]] <- predict(lm(mean_y ~ ns(water_balance, df=5) + ns(tmed, df=5), data = surf), grid)
  return(grid)
  }

predicted_values <- generate_predict(df_surfaces, v = "evi_landsat")  |> 
  inner_join(generate_predict(df_surfaces, v = "npp")) |> 
  inner_join(generate_predict(df_surfaces, v = "abi"))

# |> 
#   pivot_longer(evi_landsat:abi, values_to = "predict", names_to = "yvar")

breaks <- seq(0.05, 0.6, by=0.025)

## plot evi 
surface_evi <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = evi_landsat), 
                          show.legend = FALSE, breaks = breaks, colour = "white") + 
  #scale_fill_gradient(low = "#ffffe5", high = "#41ab5d") + 
  scale_fill_material("blue-grey") + 
  metR::geom_text_contour(aes(z = evi_landsat),
                          breaks = breaks,  colour = "black", stroke = .1, stroke.colour = "white", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "evi_landsat")),
    aes(x = water_balance, y = tmed), 
    colour = "white",
    size=.8
  ) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_bw() +
  theme(panel.border = element_blank()) +
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") 
# + ggtitle(expression(Annual~EVI[Landsat]))


## plot npp
breaks <- seq(125, 2100, by=75)
surface_npp <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = npp), 
                          show.legend = FALSE, breaks = breaks, colour = "white") +
  # scale_fill_material("brown") + 
  scale_fill_material("blue-grey") + 
  # scale_fill_gradient(low = "#fcfbfd", high = "#3f007d") + 
  # scale_fill_gradientn(colours = heat.colors(14)) + 
  metR::geom_text_contour(aes(z = npp),
                          breaks = breaks,  colour = "black", stroke = .1, stroke.colour = "white", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = "white",
    size=.8
  ) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_bw() +
  theme(panel.border = element_blank()) +
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") 
# + ggtitle(expression(Annual~NPP[MODIS]~(g~C~m^2~year^{-1})))




## plot abi
breaks <- seq(-200, 600, by=50)
surface_abi <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = abi), 
                          show.legend = FALSE, breaks = breaks, colour = "white") +
  scale_fill_material("blue-grey") + 
  # scale_fill_gradient(low = "#fcfbfd", high = "#3f007d") + 
  # scale_fill_gradientn(colours = heat.colors(14)) + 
  metR::geom_text_contour(aes(z = abi),
                          breaks = breaks,  colour = "black", stroke = .1, stroke.colour = "white", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = "white",
    size=.8
  ) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_bw() +
  theme(panel.border = element_blank()) +
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") 
# + ggtitle(expression(ABI~(g~C~m^2~year^{-1})))


  
### 
surface_evi + surface_npp + surface_abi 
  


```

### Thin splines
```{r, fig.width=12, fig.height=6}
# Using natural splines 
df_surfaces <- df_plot |>
  filter(climate_variable %in% c("water_balance", "tmed")) |> 
  filter(y_variable != "evi_modis") |> 
  mutate(climate_variable = fct_relevel(climate_variable, "water_balance","tmed")) |> 
  mutate(y_variable = fct_relevel(y_variable, "evi_landsat", "npp", "abi")) |> 
  pivot_wider(names_from = climate_variable, values_from = mean_climate) 


predictTps <- function(data, v) { 
  surf <- data |> filter(y_variable == v)
  fit <- fields::Tps(cbind(surf$water_balance, surf$tmed), surf$mean_y)
  pred <- predictSurface(fit) 
  
  g <- expand.grid(water_balance = pred$x,
                            tmed = pred$y)
  g[[v]] <- as.vector(pred$z)
  
  return(g)
}

 
point_size <- 0.6 
point_colour <- "white"




predicted_values <- predictTps(df_surfaces, v = "evi_landsat")

breaks <- seq(0.05, 0.6, by=0.025)

## plot evi 
surface_evi <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = evi_landsat), 
                          show.legend = FALSE, breaks = breaks, colour = "white") + 
  scale_fill_material("blue-grey") + 
  # metR::geom_text_contour(aes(z = evi_landsat),
  #                         breaks = breaks,  colour = "black", stroke = 0, stroke.colour = "white", 
  #                         label.placer = label_placer_n(n=1)) + 
  metR::geom_label_contour(aes(z = evi_landsat),
                          breaks = breaks,  colour = "black", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "evi_landsat")),
    aes(x = water_balance, y = tmed), 
    colour = point_colour,
    size = point_size
  ) +
  theme_bw() +
  theme(panel.grid = element_blank()
  ) + xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") + ggtitle(expression(Annual~EVI[Landsat])) +
  scale_x_continuous(limits = c(-750, 1000))  


## plot npp
breaks <- seq(150,950, by=50)
predicted_values <- predictTps(df_surfaces, v = "npp")

surface_npp <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = npp), 
                          show.legend = FALSE, breaks = breaks, colour = "white") +
  scale_fill_material("blue-grey") + 
  # metR::geom_text_contour(aes(z = npp),
  #                         breaks = breaks,  colour = "black", stroke = 0, stroke.colour = "white", 
  #                         label.placer = label_placer_n(n=1)) + 
  metR::geom_label_contour(aes(z = npp),
                          breaks = breaks,  colour = "black", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = point_colour,
    size = point_size
  ) +
  theme_bw() +
  theme(panel.grid = element_blank()) + 
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") +
  ggtitle(expression(Annual~NPP[MODIS]~(g~C~m^2~year^-1))) +
  scale_x_continuous(limits = c(-750, 1000))  




## plot abi
breaks <- seq(-200, 600, by=25)
predicted_values <- predictTps(df_surfaces, v = "abi")
surface_abi <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = abi), 
                          show.legend = FALSE, breaks = breaks, colour = "white") +
  scale_fill_material("blue-grey") + 
  # metR::geom_text_contour(aes(z = abi),
  #                         breaks = breaks,  colour = "black", stroke = 0, stroke.colour = "white", 
  #                         label.placer = label_placer_n(n=1)) + 
  metR::geom_label_contour(aes(z = abi),
                          breaks = breaks,  colour = "black", 
                          label.placer = label_placer_n(n=1)) +  
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = point_colour,
    size = point_size
  ) +
  theme_bw() +
  theme(panel.grid = element_blank()) + 
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") + ggtitle(expression(ABI~(g~C~m^2~year^-1))) +
  scale_x_continuous(limits = c(-750, 1000))  


  
### 
surface_evi + surface_npp + surface_abi 
  
```

### Thin splines expanded 
```{r, fig.width=12, fig.height=6}
# Using natural splines 
df_surfaces <- df_plot |>
  filter(climate_variable %in% c("water_balance", "tmed")) |> 
  filter(y_variable != "evi_modis") |> 
  mutate(climate_variable = fct_relevel(climate_variable, "water_balance","tmed")) |> 
  mutate(y_variable = fct_relevel(y_variable, "evi_landsat", "npp", "abi")) |> 
  pivot_wider(names_from = climate_variable, values_from = mean_climate) 


predictTps <- function(data, v) { 
  surf <- data |> filter(y_variable == v)
  fit <- fields::Tps(cbind(surf$water_balance, surf$tmed), surf$mean_y)
  pred <- predictSurface(fit, extrap = TRUE) 
  
  g <- expand.grid(water_balance = pred$x,
                            tmed = pred$y)
  g[[v]] <- as.vector(pred$z)
  
  return(g)
}

 
point_size <- 0.6 
point_colour <- "white"




predicted_values <- predictTps(df_surfaces, v = "evi_landsat")

breaks <- seq(0.05, 0.6, by=0.025)

## plot evi 
surface_evi_e <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = evi_landsat), 
                          show.legend = FALSE, breaks = breaks, colour = "white") + 
  scale_fill_material("blue-grey") + 
  # metR::geom_text_contour(aes(z = evi_landsat),
  #                         breaks = breaks,  colour = "black", stroke = 0, stroke.colour = "white", 
  #                         label.placer = label_placer_n(n=1)) + 
  metR::geom_label_contour(aes(z = evi_landsat),
                          breaks = breaks,  colour = "black", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "evi_landsat")),
    aes(x = water_balance, y = tmed), 
    colour = point_colour,
    size = point_size
  ) +
  theme_bw() +
  theme(panel.grid = element_blank()
  ) + xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") + ggtitle(expression(Annual~EVI[Landsat])) +
  scale_x_continuous(limits = c(-750, 1000))  


## plot npp
breaks <- seq(150,950, by=50)
predicted_values <- predictTps(df_surfaces, v = "npp")

surface_npp_e <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = npp), 
                          show.legend = FALSE, breaks = breaks, colour = "white") +
  scale_fill_material("blue-grey") + 
  # metR::geom_text_contour(aes(z = npp),
  #                         breaks = breaks,  colour = "black", stroke = 0, stroke.colour = "white", 
  #                         label.placer = label_placer_n(n=1)) + 
  metR::geom_label_contour(aes(z = npp),
                          breaks = breaks,  colour = "black", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = point_colour,
    size = point_size
  ) +
  theme_bw() +
  theme(panel.grid = element_blank()) + 
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") +
  ggtitle(expression(Annual~NPP[MODIS]~(g~C~m^2~year^-1))) +
  scale_x_continuous(limits = c(-750, 1000))  




## plot abi
breaks <- seq(-200, 600, by=25)
predicted_values <- predictTps(df_surfaces, v = "abi")
surface_abi_e <- predicted_values |> 
  ggplot(aes(x = water_balance, y = tmed)) +
  metR::geom_contour_fill(aes(z = abi), 
                          show.legend = FALSE, breaks = breaks, colour = "white") +
  scale_fill_material("blue-grey") + 
  # metR::geom_text_contour(aes(z = abi),
  #                         breaks = breaks,  colour = "black", stroke = 0, stroke.colour = "white", 
  #                         label.placer = label_placer_n(n=1)) + 
  metR::geom_label_contour(aes(z = abi),
                          breaks = breaks,  colour = "black", 
                          label.placer = label_placer_n(n=1)) + 
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = point_colour,
    size = point_size
  ) +
  theme_bw() +
  theme(panel.grid = element_blank()) + 
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") + ggtitle(expression(ABI~(g~C~m^2~year^-1))) +
  scale_x_continuous(limits = c(-750, 1000))  


  
### 
surface_evi_e + surface_npp_e + surface_abi_e 
  



```


## Combined 
```{r, fig.width=13, fig.height=13}

cp <- plot_wb / plot_tmed / (surface_evi + surface_npp + surface_abi)

cp 
ggsave(
  cp, 
  file = "output/combined_fig.png",
  dpi = 300,
  width = 13, height = 13
)

```


```{r, fig.width=13, fig.height=13}
cpe <- plot_wb / plot_tmed / (surface_evi_e + surface_npp_e + surface_abi_e)

cpe
ggsave(
  cpe, 
  file = "output/combined_fig_extrapolated.png",
  dpi = 300,
  width = 13, height = 13
)
  
  
```




```{r, eval=FALSE, echo=FALSE}
## Test Surfaces 

### Simple linear combination 
d <- df_surfaces |> 
  filter(y_variable == "npp") |> 
  dplyr::select(z = mean_y, wb = water_balance, tmed)

## A 
# https://stackoverflow.com/questions/77853257/ggplot2-geom-contour-how-to-remove-the-gray-panel-around-a-plot
d_grid <- expand.grid(
  wb = seq(min(d$wb), max(d$wb), 20),
  tmed = seq(min(d$tmed), max(d$tmed), 0.1))

d_grid$z <- predict(lm(z ~ wb * tmed, data = d), d_grid)

breaks <- seq(125, 1675, by=75)
d_grid |> 
  ggplot(aes(x = wb, y = tmed)) + 
  geom_contour_filled(aes(z=z), breaks = breaks,
                      show.legend = FALSE) + 
  geom_textcontour(aes(z=z), size = 3, breaks = breaks, colour = "white") +
  geom_point(
    data = 
      (df_surfaces |> 
         filter(y_variable == "npp")),
    aes(x = water_balance, y = tmed), 
    colour = "white",
    size=.6
  ) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_bw() +
  theme(panel.border = element_blank()) +
  xlab("Water Balance (mm)") +
  ylab("Annual Mean Temperature (ºC)") +
  ggtitle(expression(Annual~NPP[MODIS]~(g~C~m^2~year^{-1})))

```



```{r, eval=FALSE, echo=FALSE}
#### TEST ajustes

g <- df_plot |> filter(climate_variable == "water_balance") |> 
  filter(y_variable == "npp") |> 
  pivot_wider(names_from = climate_variable, values_from = mean_climate) |> 
  pivot_wider(names_from = y_variable, values_from = mean_y)

# ver https://osf.io/7gkny/
# https://mhasoba.github.io/TheMulQuaBio/notebooks/20-ModelFitting-NLLS.html 

g |> dplyr::select(water_balance, evi_landsat) |> write_csv("/Users/ajpelu/Desktop/test.csv")

# Get init 
init_aysmpOff <- as.data.frame(t(getInitial(npp ~ SSasympOff(water_balance, Asym, lrc, c0), data = g)))
init_aysmp <- as.data.frame(t(getInitial(npp ~ SSasymp(water_balance, Asym, R0, lrc), data = g)))
init_gomp <- as.data.frame(t(getInitial(npp ~ SSgompertz(water_balance, Asym, b2, b3), data = g)))
init_logist <-  as.data.frame(t(getInitial(npp ~ SSlogis(water_balance, Asym, xmid, scal), data = g)))
  
  


g |> 
  ggplot(aes(x = water_balance, y = evi_landsat)) + 
  geom_point() +
          geom_smooth(aes(), 
              method = "nls", 
              formula = y~a + b * (exp(-exp(-c * (x - d)))), 
              se =  FALSE, # this is important 
              method.args =list(start = c(a = 0.15, b = 0.3, c = 0.005, d = -420),        
                                control=nls.control(maxiter=1000)),
              size = 1.5, 
              colour = "orange") +
  
  
  geom_smooth(aes(), 
              method = "nls", 
              # formula = y~Asym/(1+exp(-(x-xmid)/scal)), 
              formula = y~Asym*(1 - exp(-exp(lrc)*(x - c0))),
              se =  FALSE, # this is important 
              method.args =list(start=init_aysmpOff,
                                control=nls.control(maxiter=1000)),
              size = 1.5, 
              colour = "black") +
  geom_smooth(aes(), 
              method = "nls", 
              formula = y~Asym+(R0-Asym)*exp(-exp(lrc)*x),
              se =  FALSE, # this is important 
              method.args =list(start=init_aysmp,
                                control=nls.control(maxiter=1000)),
              size = 1.5, 
              colour = "blue") +
    geom_smooth(aes(), 
              method = "nls", 
              formula = y~Asym*exp(-b2*b3^x),
              se =  FALSE, # this is important 
              method.args =list(start=init_gomp,
                                control=nls.control(maxiter=1000)),
              size = 1.5, 
              colour = "red") +
      geom_smooth(aes(), 
              method = "nls", 
              formula = y~Asym/(1+exp((xmid-x)/scal)),
              se =  FALSE, # this is important 
              method.args =list(start=init_logist,
                                control=nls.control(maxiter=1000)),
              size = 1.5, 
              colour = "green") 

+
        geom_smooth(aes(), 
              method = "nls", 
              formula = y~a+b(exp(−exp(−c(x−d)))),
              se =  FALSE, # this is important 
              method.args =list(start=list(a = 0.15, b = .3, c = 0.005 , d = -420),
                                control=nls.control(maxiter=1000)),
              size = 1.5, 
              colour = "orange") 
  
```

