---
title: "Figure: Climate sites "
output: workflowr::wflow_html
bibliography: references.bib
cls: ecology-letters.csl
editor_options:
  chunk_output_type: console
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10, fig.height = 7
)
```


```{r}
library(tidyverse)
library(ggbreak)
library(grid)
library(magick)


source("scripts/aux.R")
```

```{r}
avg_yearly <- read_csv("data/dendroadaptamed_climate_avg_yearly.csv") |> 
  mutate(elev_code = fct_recode(elev_code, `low-Dec` = "low2")) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high"))

geodf <- terra::vect( "data/geoinfo/geoinfo_dendro_adaptamed_pinus.shp") |> as.data.frame() |>
  unite("sp_elev", c(sp_code, elev_code), remove = FALSE) |> 
  dplyr::select(sp_elev, elev) |> 
  separate(sp_elev, into = c("sp_code", "elev_code"), remove = FALSE) |> 
  mutate(elev_code = fct_recode(elev_code, `low-Dec` = "low2")) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high"))
  
```


```{r}
aux <- avg_yearly |> 
  dplyr::select(-annual_sd, -annual_se) |> 
  pivot_wider(names_from = var, values_from = annual_value) 


lower_ci <- function(mean, se, n, conf_level = 0.95){
  lower_ci <- mean - qt(1 - ((1 - conf_level) / 2), n - 1) * se
  return(lower_ci)
}

upper_ci <- function(mean, se, n, conf_level = 0.95){
  upper_ci <- mean + qt(1 - ((1 - conf_level) / 2), n - 1) * se
  return(upper_ci)
}

aux_avg <- aux |> 
  pivot_longer(tmed:prec, names_to = "var") |>  
  group_by(sp_code, elev_code, sp_elev, var) |> 
  summarise(
    mean = mean(value, na.rm = TRUE), 
    sd = sd(value, na.rm = TRUE), 
    se = sd / sqrt(length(value)), 
    n = length(value)
  ) |> 
  pivot_wider(values_from = c(mean, sd, se, n), names_from = var)

aux_avg1 <- aux_avg |> 
  mutate(lower_prec = lower_ci(mean = mean_prec, se = se_prec, n = n_prec), 
         upper_prec = upper_ci(mean = mean_prec, se = se_prec, n = n_prec), 
         lower_tmed = lower_ci(mean = mean_tmed, se = se_tmed, n = n_tmed),
         upper_tmed = upper_ci(mean = mean_tmed, se = se_tmed, n = n_tmed),
         ) |> 
  inner_join(geodf) |> 
  rename(prec = mean_prec, 
         tmed = mean_tmed)

```


## Figure 1 v1 
```{r}
ggplot(data = aux, 
       aes(y = tmed, x = prec, colour = sp_code)) +
  geom_point(aes(shape = elev_code, fill=sp_code), size = 1.4, alpha = .4) +
  geom_errorbar(
    data = aux_avg1, aes(y = tmed,
                        ymin = lower_tmed,
                        ymax = upper_tmed, 
                        x = prec),
    linewidth = .7) +
  geom_errorbarh(
    data = aux_avg1, aes(x = prec, 
                         xmin = lower_prec, 
                         xmax = upper_prec, 
                        y = tmed), linewidth = .7) +
  geom_point(data = aux_avg1, 
             aes(x = prec, y = tmed, shape = elev_code, fill = sp_code),
             size = 2.9, color = "black", stroke = 1) +  # Set color to "black" for border
  scale_colour_manual(values = colours_sp, name = "Species",
                      guide = guide_legend(label.theme = element_text(face = "italic"))) +
  scale_shape_manual(values = shape_elev, name = "Elevation") + 
  scale_fill_manual(values = colours_sp, name = "Species", 
                    guide = guide_legend(label.theme = element_text(face = "italic"))) + 
  scale_x_continuous(limits = c(0,2000), 
                     breaks = c(0, 250, 500, 750, 1500, 2000)) + 
  xlab("Annual precipitation (mm)") + 
  ylab("Average annual mean temperature (ºC)") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.border = element_blank(),
    axis.title = element_text(face="plain", colour = "black", size=12),
    axis.text.y=element_text(face="plain", colour = "black", size=11),
    axis.text.x=element_text(face= "plain", colour = "black", size=11),
    axis.ticks = element_line(colour="black", size= 0.3)
  ) + 
  guides(
    fill = guide_legend(title = "Species", 
                        override.aes = list(shape = 19, color = colours_sp)),
    shape = guide_legend(override.aes = list(color = "black", fill = "white"))
  ) +  
  scale_x_cut(breaks = 1000, which=2, scales=c(0.2)) 

# Los errores que salen 260 rows son los datos de temperaturas que faltan para los datos de prec antes de 1970
```


## Figure 1 v2 
```{r}
img_pines <- magick::image_read("data/image_pinus/pinus_juntos.png")



fig_clima <- ggplot(aux, aes(y = tmed, x = prec, colour = sp_code)) +
  geom_point(aes(shape = elev_code, fill = sp_code), size = 1.4, alpha = .4) +
  geom_errorbar(
    data = aux_avg1, aes(
      y = tmed,
      ymin = lower_tmed,
      ymax = upper_tmed,
      x = prec), linewidth = .8) +
  geom_errorbarh(
    data = aux_avg1, aes(
      xmin = lower_prec,
      xmax = upper_prec,
      y = tmed), linewidth = .8) +
  geom_point(
    data = aux_avg1,
    aes(x = prec, y = tmed, shape = elev_code, fill = sp_code),
    size = 2.9, color = "black", stroke = 1) + # Set color to "black" for border
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") +
  scale_x_continuous(limits = c(0, 1750), breaks = seq(0, 1750, 250)) +
  xlab("Annual precipitation (mm)") +
  ylab("Average annual mean temperature (ºC)") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    legend.position = c(0.1, 0.15),
    legend.background = element_blank()
    ) +
  guides(
    fill = "none",
    color = "none",
    shape = guide_legend(override.aes = list(color = "black", fill = "white"))) +
  annotation_custom(
  grid::rasterGrob(img_pines), xmin = 750, xmax = 1750, ymin = 13, ymax = 16
) + 
  annotate("text", x=850, y=13, label= "italic(halepensis)", parse = TRUE, size = 3.5) +
  annotate("text", x=1150, y=13, label= "italic(pinaster)", parse = TRUE, size = 3.5) +
  annotate("text", x=1450, y=13, label= "italic(nigra)", parse = TRUE, size = 3.5) +
  annotate("text", x=1700, y=13, label= "italic(sylvestris)", parse = TRUE, size = 3.5)

fig_clima
```


```{r}
ggsave(
  fig_clima, 
  file = "output/plot_clima.png",
  dpi = 300,
  width = 9.5, height = 10,
  units = "cm"
)
```


```{r}
fig_climav2 <- ggplot(aux, aes(y = tmed, x = prec, 
                colour = sp_code)) +
  geom_point(aes(shape = elev_code, fill = sp_code), size = 1.4, alpha = .4) +
  geom_errorbar(
    data = aux_avg1, aes(
      y = tmed,
      ymin = lower_tmed,
      ymax = upper_tmed,
      x = prec), linewidth = .8) +
  geom_errorbarh(
    data = aux_avg1, aes(
      xmin = lower_prec,
      xmax = upper_prec,
      y = tmed), linewidth = .8) +
  geom_point(
    data = aux_avg1,
    aes(x = prec, y = tmed, shape = elev_code, fill = sp_code),
    size = 2.9, color = "black", stroke = 1) + # Set color to "black" for border
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") +
  scale_x_continuous(limits = c(0, 1750), breaks = seq(0, 1750, 250)) +
  xlab("Annual precipitation (mm)") +
  ylab("Average annual mean temperature (ºC)") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    legend.position = c(0.1, 0.15),
    legend.background = element_blank()
    ) +
  guides(
    fill = "none",
    color = "none",
    shape = guide_legend(override.aes = list(color = "black", fill = "white")))

```


```{r}
ggsave(
  fig_climav2, 
  file = "output/plot_clima_v2.svg",
  dpi = 300,
  width = 9.5, height = 10,
  units = "cm"
)
```

```{r}
fig_clima_en_mapa <- ggplot(aux, aes(y = tmed, x = prec, colour = sp_code)) +
  geom_point(aes(shape = elev_code, fill = sp_code), size = 1.2, alpha = .4) +
  geom_errorbar(
    data = aux_avg1, aes(
      y = tmed,
      ymin = lower_tmed,
      ymax = upper_tmed,
      x = prec), colour = "black", linewidth = .6) +
  geom_errorbarh(
    data = aux_avg1, aes(
      xmin = lower_prec,
      xmax = upper_prec,
      y = tmed), colour = "black",
    linewidth = .6) +
   geom_point(
    data = aux_avg1,
    aes(x = prec, y = tmed, shape = elev_code, fill = sp_code),
    size = 2, color = "black", stroke = .4) + # Set color to "black" for border
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") +
  scale_x_continuous(limits = c(0, 1750), breaks = seq(0, 1750, 250)) +
  xlab("Annual precipitation (mm)") +
  ylab("Average annual mean temperature (ºC)") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    legend.position = c(0.15, 0.10),
    legend.background = element_blank(),
    legend.text = element_text(size = 6),
    legend.key.size = unit(.2, "cm"),
    axis.title = element_text(size = 10), 
    axis.text = element_text(size = 8)
    ) +
  guides(
    fill = "none",
    color = "none",
    shape = guide_legend(override.aes = list(color = "black", fill = "white", size = 1.5))) +
  annotation_custom(
  grid::rasterGrob(img_pines), xmin = 750, xmax = 1750, ymin = 13, ymax = 16)
 
#   annotate("text", x=850, y=13, label= "italic(halepensis)", parse = TRUE, size = 3.5) +
#   annotate("text", x=1150, y=13, label= "italic(pinaster)", parse = TRUE, size = 3.5) +
#   annotate("text", x=1450, y=13, label= "italic(nigra)", parse = TRUE, size = 3.5) +
#   annotate("text", x=1700, y=13, label= "italic(sylvestris)", parse = TRUE, size = 3.5)



ggsave(
  fig_clima_en_mapa, 
  file = "output/plot_clima_en_mapa.png",
  dpi = 300,
  width = 9.5, height = 10,
  units = "cm"
)

ggsave(
  fig_clima_en_mapa, 
  file = "output/plot_clima_en_mapa.svg",
  dpi = 300,
  width = 9.5, height = 10,
  units = "cm"
)

```

### Temporal analysis (MK) 

```{r}
library(Kendall)
library(trend)

# Tmed 1971, Prec 1970 

aux <- aux |> mutate(elev_code = case_when(
    elev_code == "low-D" ~ "low-Dec",
    TRUE ~ as.character(elev_code)
  )) 


mk_tmed <- aux |> 
  dplyr::select(-prec) |> 
  na.omit() |> 
  ungroup() |> 
  group_by(sp_code, elev_code, sp_elev)|> 
  summarise(across(c(tmed), ~MannKendall(.)$tau, .names ="tau"),
            across(c(tmed), ~MannKendall(.)$sl, .names ="pvalue_mk"),
            across(c(tmed), ~trend::sens.slope(.)$estimate, .names ="senslope"),
            across(c(tmed), ~trend::sens.slope(.)$p.value, .names ="pvalue_sen")) |> 
  mutate(ypos = 
           case_when(
             elev_code == "low" ~ 14,
             elev_code == "low-Dec" ~ 8,
             elev_code == "medium" ~ 15,
             elev_code == "high" ~ 16), 
         p_value_string = symnum(pvalue_mk, corr = FALSE,
               cutpoints = c(0,  .001,.01,.05, 1),
               symbols = c("***","**","*","")), 
         variable = "tmed") |> 
  mutate(taulabel = paste(expression(tau), "==", paste0('"', round(tau, 3), p_value_string, '"'))) |> 
  mutate(
    Specie = paste0("P. ", sp_code)
  ) |> 
  mutate(taulabel = gsub("-", "\U2212", taulabel))


mk_tmed <- mk_tmed |> 
  mutate(ypos = 
           case_when(
             sp_code == "halepensis" & elev_code == "low" ~ 8,
             sp_code == "halepensis" & elev_code == "medium" ~ 9,
             sp_code == "halepensis" & elev_code == "high" ~ 10,
             TRUE ~ ypos)) 

mk_prec <- aux |> 
  ungroup() |> 
  filter(year > 1969) |> 
  group_by(sp_code, elev_code, sp_elev)|> 
  summarise(across(c(prec), ~MannKendall(.)$tau, .names ="tau"),
            across(c(prec), ~MannKendall(.)$sl, .names ="pvalue_mk"),
            across(c(prec), ~trend::sens.slope(.)$estimate, .names ="senslope"),
            across(c(prec), ~trend::sens.slope(.)$p.value, .names ="pvalue_sen")) |> 
  mutate(ypos = 
           case_when(
             elev_code == "low" ~ 1200,
             elev_code == "low-Dec" ~ 1050,
             elev_code == "medium" ~ 1350,
             elev_code == "high" ~ 1500), 
         p_value_string = symnum(pvalue_mk, corr = FALSE,
               cutpoints = c(0,  .001,.01,.05, 1),
               symbols = c("***","**","*","")),
         variable = "prec") |> 
  mutate(taulabel = paste(expression(tau), "==", paste0('"', round(tau, 3), p_value_string, '"'))) |> 
  mutate(
    Specie = paste0("P. ", sp_code)
  ) |> 
  mutate(taulabel = gsub("-", "\U2212", taulabel))



mk <- bind_rows(mk_prec, mk_tmed)
```



```{r}
clima <- aux |> 
  filter(year > 1969) |>
  dplyr::select(-tmax, -tmin) |> 
  pivot_longer(c(prec, tmed), names_to = "variable", values_to = "mean") |> 
  mutate(Specie = paste0("P. ", sp_code)) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high")) 


to_label <- as_labeller(c(
 "tmed" = "Annual Mean Temperature (ºC)", 
 "prec" = "Precipitation (mm)"))

colours_elev <- c("low-Dec" = "#8c510a",
                  "low" ="#fc8d59",
                  "medium" = "#2166ac",
                  "high" = "#72A55A")

figura_ts_clima <- clima |> 
  ggplot(aes(x = year, y = mean, group = elev_code, colour = elev_code)) +
  geom_line() +
  facet_grid(variable~factor(Specie, levels = c("P. halepensis", "P. pinaster", "P. nigra", "P. sylvestris")), 
             scales = "free_y", 
             switch = "y",
             labeller = labeller(variable = to_label)) +
   scale_colour_manual(values = colours_elev, name = "",
                      guide = guide_legend(override.aes = list(linewidth = 2))) + 
  scale_fill_manual(values = colours_elev, name="") + 
  theme_bw() +
  ylab("") +  xlab("") + 
  theme(
    text = element_text(family = "Helvetica"),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    strip.text.x = element_text(face = "italic", size = 13),
    strip.text.y = element_text(face = "bold", size = 12),
    strip.background = element_blank(),
    strip.placement = "outside", 
    legend.position = "bottom",
    legend.text = element_text(size = 11),
    axis.text = element_text(size = 11)
  ) +
  scale_x_continuous(limits = c(1970, 2021), breaks = seq(1971, 2020, by = 10)) +
  geom_text(x = 1971, aes(y = ypos, label = taulabel), data = mk, parse = TRUE, show.legend = FALSE, hjust = "left", size = 4.5)

figura_ts_clima 
```

```{r}
ggsave(
  figura_ts_clima, 
  file = "output/plot_ts_clima.jpg",
  dpi = 400,
  width = 7.09*1.3*1.5, height = 7.09*1.3*0.8
)
```




```{r}
#| echo: false
#| eval: false
temp_all <- clima |>
  filter(variable == "tmed") |> 
  rename(value = mean) |>
  mutate(decade = floor(year/10)*10) 

temp_decade_mean <- temp_all |>
  group_by(decade, variable, Specie, elev_code) |> 
  summarise(mean = mean(value, na.rm = TRUE), 
            sd = sd(value, na.rm=TRUE), 
            se = sd/sqrt(length(value))) |> 
  ungroup() |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high"))



t7010_mean <- temp_decade_mean |> 
  filter(decade %in% c(1970, 2010)) |> 
  mutate(decade = as.factor(decade)) |> 
  mutate(decade = fct_relevel(decade, "1970", "2010"))

t7010_all <- temp_all |> 
  filter(decade %in% c(1970, 2010)) |> 
  mutate(decade = as.factor(decade)) |> 
  mutate(decade = fct_relevel(decade, "1970", "2010"))


temp_mean_sp <- temp_all |>
    filter(decade %in% c(1970, 2010)) |> 
  group_by(decade, variable, Specie) |> 
  summarise(mean = mean(value, na.rm = TRUE), 
            sd = sd(value, na.rm=TRUE), 
            se = sd/sqrt(length(value))) |> 
  ungroup() 






custom_position = position_dodge(width = 0.3)





ggplot(t7010_mean, 
       aes(y = mean, x = decade, 
                  group = elev_code, colour = elev_code)) + 
  geom_jitter(data = t7010_all, 
              aes(y = value, x = as.factor(decade), 
                  group = elev_code, colour = elev_code), 
              alpha = 0.3, size = .75, stroke = 0.5, 
              position = custom_position, show.legend = FALSE) +
  geom_errorbar(aes(ymin =mean-1.96*se, ymax=mean+1.96*se), position = custom_position) +
  facet_wrap(~Specie) 
  
  
  
  




clima_decade <- temp_all |>
  group_by(decade, variable, Specie, elev_code) |> 
  summarise(mean = mean(value, na.rm = TRUE), 
            sd = sd(value, na.rm=TRUE), 
            se = sd/sqrt(length(value))) |> 
  ungroup() |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high"))


clima_decade_all <- clima_decade |> 
  rename(value = mean) |>
  group_by(decade, variable, Specie) |> 
  summarise(mean = mean(value, na.rm = TRUE), 
            sd = sd(value, na.rm=TRUE), 
            se = sd/sqrt(length(value))) |> 
  ungroup() 

colours_elev <- c("low-Dec" = "#8c510a",
                  "low" ="#fc8d59",
                  "medium" = "#2166ac",
                  "high" = "#72A55A")






ggplot(data = (clima_decade |> 
                 filter(variable == "tmed") |> 
                 filter(decade %in% c(1970, 2010))), 
       aes(y = mean, x = Specie, group = decade, colour = decade)) + 
  geom_point()
  geom_errorbar(aes(ymin=mean-1.96*se, ymax=mean+1.96*se))

   
```

