---
title: "Figure: Time series Dendrochronology and Remote Sensing"
output: workflowr::wflow_html
bibliography: references.bib
cls: ecology-letters.csl
editor_options:
  chunk_output_type: console
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10, fig.height = 7
)
```


```{r}
library(tidyverse)
library(kableExtra)
library(ggh4x)

source("scripts/aux.R")
```

## Figure S1

```{r}
abi <- read_csv("data/dendroadaptamed_abi.csv") |> 
  rename(mean = IBT_ag_m2) |> 
  mutate(se = NA, sd = NA, variable = "abi")

npp <- read_csv("data/dendroadaptamed_npp_modis.csv") |> 
  rename(mean = npp) |> 
  mutate(se = NA, sd = NA, variable = "npp") |> 
  dplyr::select(-npp_qc, -sp_elev, -gpp, -Specie)

evi_landsat <- read_csv("data/dendroadaptamed_iv_landsat.csv") |> 
  filter(iv == "evi") |> 
  dplyr::select(year, sp_code, elev_code, mean, sd, se) |> 
  mutate(variable = "evi_landsat")

evi_modis <- read_csv("data/dendroadaptamed_iv_modis.csv") |> 
  filter(variable == "evi") |> 
  filter(season == "yearly") |> 
  dplyr::select(year, sp_code, elev_code, mean, sd, se) |> 
  mutate(variable = "evi_modis")


df <- bind_rows(
  abi, evi_landsat, evi_modis, npp) |> 
 # mutate(elev_code = fct_recode(elev_code, `low-Dec` = "low2")) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high"))

```

```{r}
mk_evi_landsat <- read_csv("data/dendroadaptamed_iv_landsat_trend.csv") |> 
  dplyr::select(sp_code, elev_code, sp_elev, tau = mean_tau, pvalue_mk = mean_pvalue_mk,  senslope = mean_senslope, pvalue_sen= mean_pvalue_sen, ypos, p_value_string, taulabel) |> 
   mutate(variable = "evi_landsat")
  
mk_npp <- read_csv("data/dendroadaptamed_npp_modis_trend.csv") |> 
  rename(tau = npp_tau, 
         pvalue_mk = npp_pvalue_mk,
         senslope = npp_senslope,
         pvalue_sen = npp_pvalue_sen) |> 
  mutate(variable = "npp") |> 
  mutate(ypos2 = case_when(
    ypos == 1000 ~ 800, 
    ypos == 1025 ~ 900, 
    ypos == 1050 ~ 1000, 
    ypos == 1075 ~ 1075)) |> 
  dplyr::select(-ypos, -Specie) |> rename(ypos = ypos2)

mk_abi <- read_csv("data/dendroadaptamed_abi_trend.csv") |> 
    rename(tau = mean_tau, 
         pvalue_mk = mean_pvalue_mk,
         senslope = mean_senslope,
         pvalue_sen = mean_pvalue_sen) |> 
  mutate(variable = "abi") |> 
  mutate(ypos2 = case_when(
    ypos == 510 ~ 485, 
    ypos == 540 ~ 530, 
    ypos == 570 ~ 570, 
    ypos == 480 ~ 440)) |> 
  dplyr::select(-ypos, -Specie) |> rename(ypos = ypos2)



mk <- bind_rows(mk_evi_landsat, mk_npp, mk_abi) |> 
  mutate(variable = fct_relevel(variable, "evi_landsat", "npp", "abi")) |> 
  # mutate(elev_code = fct_recode(elev_code, `low-Dec` = "low2")) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high"))
```


```{r, fig.height=9, fig.width=12}
to_label <- as_labeller(c(
 "evi_landsat" = "Annual~EVI[Landsat]", 
 "npp" = "Annual~NPP[MODIS]~(g~C~m^2~year^{-1})",
 "abi" = "ABI~(g~C~m^2~year^{-1})"
), default = label_parsed)


fig_ts <- df |> 
  filter(variable != "evi_modis") |>
  mutate(variable = fct_relevel(variable, "evi_landsat", "npp", "abi")) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high")) |> 
  ggplot(aes(x = year, y = mean, group = elev_code, colour = elev_code)) +
  geom_ribbon(aes(ymin = (mean - se), ymax=(mean+se), fill=elev_code), colour=NA, alpha=.2) + 
  geom_line() +
  facet_grid(variable~factor(sp_code, levels = c("halepensis", "pinaster", "nigra", "sylvestris")), 
             scales = "free_y", 
             switch = "y", 
             labeller = labeller(variable = to_label)) + 
  scale_colour_manual(values = colours_elev, name = "") +
  scale_fill_manual(values = colours_elev, name="") + 
  theme_bw() +
  ylab("") +  xlab("") + 
  theme(
    panel.grid = element_blank(),
    panel.background = element_blank(),
    strip.text.x = element_text(face = "italic", size = 10),
    strip.text.y = element_text(face = "bold", size = 10),
    strip.background = element_blank(),
    strip.placement = "outside", 
    legend.position = "bottom"
  ) +
  scale_x_continuous(limits = c(1980, 2021), breaks = seq(1950, 2020, by = 10), 
                     sec.axis = dup_axis()) +
  scale_y_continuous(sec.axis = dup_axis()) +
  geom_text(x = 1980, aes(y = ypos, label = taulabel), data = mk, parse = TRUE, show.legend = FALSE, hjust = "left")


fig_ts
```



```{r}
ggsave(
  fig_ts, 
  file = "output/plot_ts_dendro_remote.jpg",
  dpi = 300,
  width = 12, height = 8
)
```




### Explore trends

```{r}
overview_trends <- mk |>
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high")) |> 
  mutate(sp_code = fct_relevel(sp_code, "halepensis","pinaster", "nigra", "sylvestris")) |> 
  mutate(var = fct_relevel(variable, "evi_landsat","npp", "abi")) |> 
  mutate(border_color = ifelse(is.na(p_value_string), "transparent", "black")) |> 
  ggplot(aes(x=sp_code, y=elev_code, fill = tau)) + 
  geom_point(aes(size = tau, shape = var, colour = border_color), position = position_jitterdodge(jitter.width = 0, dodge.width = 0.4)) + 
  scale_fill_gradientn(colours = c("#d7191c", "#ffffbf", "#2b83ba"), limits = c(-1, 1), breaks = c(-.75, 0, .75)) +
  scale_colour_identity() + 
  scale_size_continuous(range = c(1,10)) +
  scale_shape_manual(values = c(21,22,24)) +
  ylab("Elevation gradient") +
  xlab("Drought tolerance gradient") +
  theme_bw() +
  theme(
    axis.text.x = element_text(face = "italic")
  )

overview_trends

ggsave(
  overview_trends, 
  file = "output/plot_trends_overview.jpg",
  dpi = 300,
  width = 12, height = 8
)
```



```{r}
df_increment <- mk |> 
  dplyr::select(variable, sp_code, elev_code, sp_elev, tau) |> 
  group_by(variable, sp_code) |> 
  mutate(increment = abs(tau)/(abs(tau[elev_code == "low"]))) |> 
  ungroup()
```


```{r}
mk |> 
  ungroup() |> 
  relocate(variable) |> 
  dplyr::select(-ypos, -p_value_string, -taulabel, -sp_elev, -senslope, -pvalue_sen) |> 
  kbl(
    digits = c(0,0,3,4,5,4),
    caption = "Mann-Kendall temporal trend") |> 
    column_spec(3:5, bold = ifelse(mk$pvalue_mk < 0.05, TRUE, FALSE)) |> 
  column_spec(1, italic = TRUE) |> 
  collapse_rows(columns = 1:2) |> 
    kable_paper("hover", full_width = F)

```



### Explore tau by gradients 
```{r}
#| fig.height: 7 
#| fig.width: 7
tau_by_gradients <- mk |>
  mutate(elev_code = fct_relevel(elev_code, "low-Dec","low", "medium", "high")) |> 
  mutate(sp_code = fct_relevel(sp_code, "halepensis","pinaster", "nigra", "sylvestris")) |> 
  ggplot(aes(x=sp_code,y=tau, group = elev_code, colour = elev_code)) + 
  geom_point(aes(size = tau)) +
  geom_line() +
  facet_wrap(~variable, ncol = 1, scales = "free_y") +
  theme_bw() + 
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "white"),
    strip.text = element_text(face = "bold", size = 14)
  ) +
   scale_colour_manual(values = colours_elev, name = "") +
  xlab("Species (sort by drought tolerance)")


tau_by_gradients
ggsave(
  tau_by_gradients, 
  file = "output/plot_trends_tau_gradients.jpg",
  dpi = 300,
  width = 7, height = 7
)

```


### Mean values (along gradients)

```{r}
#| fig.height: 7 
#| fig.width: 5
df_summary <- df |> 
  filter(variable != "evi_modis") |> 
  group_by(variable, sp_code, elev_code) |> 
  rename(value = mean) |> 
  summarise(mean = mean(value, na.rm = TRUE), 
            sd = sd(value, na.rm = TRUE), 
            se = sd/sqrt(length(value))) |> 
  mutate(variable2 = case_when(
    variable == "abi" ~ "ABI~(g~C~m^2~year^{-1})", 
    variable == "npp" ~ "Annual~NPP[MODIS]~(g~C~m^2~year^{-1})",
    variable == "evi_landsat" ~ "Annual~EVI[Landsat]"
  )) |> 
  ungroup()


label_landsat <- "Annual~EVI[Landsat]"
label_npp <- "Annual~NPP[MODIS]~(g~C~m^2~year^{-1})"
label_abi <- "ABI~(g~C~m^2~year^{-1})"


y_scales <- list(
  scale_y_continuous(limits = c(0.15, 0.45)),
  scale_y_continuous(limits = c(250,1000)),
  scale_y_continuous(limits = c(0, 300))
)



plot_avg_values <- df_summary |> 
   mutate(sp_code = fct_relevel(sp_code, "halepensis","pinaster", "nigra", "sylvestris")) |> 
  ggplot(aes(x=sp_code,y=mean, group = elev_code, colour = elev_code)) + 
  geom_point(size = 1.2) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1) +  
  geom_line() +
  theme_bw() + 
  theme(
    panel.grid = element_blank(),
    strip.background = element_blank(),
    strip.placement = "outside",
    legend.position = "top", 
    axis.text.x = element_text(face = "italic"),
    strip.text = element_text(face = "bold", size = 9)
  ) + 
   scale_colour_manual(values = colours_elev, name = "") +
  xlab("") + 
  ylab("") + 
    facet_wrap(~factor(variable2, c("Annual~EVI[Landsat]", 
                                    "Annual~NPP[MODIS]~(g~C~m^2~year^{-1})",
                                    "ABI~(g~C~m^2~year^{-1})")),
             scales = "free_y", 
                     labeller = label_parsed, 
                     strip.position = "left",
             ncol = 1) 

# + ggh4x::facetted_pos_scales(y = y_scales) # custom scales

plot_avg_values
ggsave(
  plot_avg_values, 
  file = "output/plot_avg_gradient.jpg",
  dpi = 300,
  width = 5, height = 7
)

```





```{r, fig.height=5, fig.width=5}
#| eval: false

## Comparisons among variables
## Revisar 
label_landsat <- "Annual~EVI[Landsat]"
label_npp <- "Annual~NPP[MODIS]~(g~C~m^2~year^{-1})"
label_abi <- "ABI~(g~C~m^2~year^{-1})"


abi_npp <- df |> filter(variable %in% c("abi", "npp")) |> 
  pivot_wider(values_from = mean, names_from = variable) |> 
  filter(year > 1999) |> 
  filter(!is.na(abi)) 

|> 
  # filter(!is.na(npp))


lm_abi_npp <- lm(npp ~ abi, data=abi_npp)

abi_npp |> 
  filter(year > 1999) |> 
  ggplot(aes(x=npp, y = abi, colour = sp_code)) + 
  geom_point(aes(shape = elev_code, fill = sp_code)) +
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") + 
  theme_bw() + 
    theme(
    panel.grid = element_blank(), 
    legend.background = element_blank(),
    legend.position = c(.1,.7)
  ) +
  ylab(parse(text=label_abi)) +
  xlab(parse(text=label_npp)) 

# 
# model <- lm(abi ~ npp, data = abi_npp)
# segmented_model <- segmented(model, seg.Z = ~npp)
# 
# seg_preds <- as.vector(predict(segmented_model))
# seg_res <- abi_npp$abi - seg_preds
# 
# 
# abi_npp <- abi_npp |> 
#   rowwise() |> 
#   mutate(seg_preds = predict(segmented_model))
# 
# 
# # Plot the original data with the fitted model
# plot(
#   abi_npp$npp, abi_npp$abi,
#   main = "Piecewise Regression Fit",
#   xlab = "Independent Variable (x)",
#   ylab = "Dependent Variable (y)",
#   col = "blue"
# )
# lines(abi_npp$npp, seg_preds,col = "red", lwd = 2)
# 
# 
# 
# ggg <- data.frame(npp = abi_npp$npp, 
#                   abi = abi_npp$abi)
# ggg$seg = seg_preds


abi_evi <- df |> 
  filter(variable %in% c("abi", "evi_landsat")) |> 
  dplyr::select(-se, -sd) |> 
  pivot_wider(values_from = mean, names_from = variable) 

lm_abi <- lm(evi_landsat ~ abi, data=abi_evi)

abi_evi |> 
  filter(year > 1999) |> 
  ggplot(aes(x=evi_landsat, y = abi)) + 
  geom_point(aes(shape = elev_code, fill = sp_code, colour = sp_code)) +
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") + 
  theme_bw() +
  scale_y_continuous(limits = c(0,500)) + 
  scale_x_continuous(limits = c(0,.5)) +
  # geom_abline(slope = coef(lm_abi)[["abi"]], 
  #             intercept = coef(lm_abi)[["(Intercept)"]]) +
  # geom_abline(slope = 0.001, colour = "gray") + 
  theme(
    panel.grid = element_blank(), 
    legend.background = element_blank(),
    legend.position = c(0.3,0.8)
  ) +
  xlab(parse(text=label_abi)) +
  ylab(parse(text=label_landsat)) +
  guides(
    shape = guide_legend(
      title = "Elevation", 
      title.position = "top", 
      label.position = "right", 
      nrow = 1
    ),
    colour = guide_legend(
      title = "Species", 
      title.position = "top", 
      label.position = "right", 
      nrow = 1
    ),
    fill = "none" # Remove the fill legend
  ) +
   geom_smooth(method = "lm", aes(fill = sp_code, colour = sp_code), se=FALSE) 

 # stat_cor(label.y = .48, 
 #           aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~"))) +
 #  ggpubr::stat_regline_equation(label.x = 50, label.y = 0.45,
 #                                formula = y ~ x)
 #  



npp_evi <- df |> 
  filter(variable %in% c("npp", "evi_landsat")) |> 
  dplyr::select(-se, -sd) |> 
  pivot_wider(values_from = mean, names_from = variable) 


init <- as.data.frame(t(getInitial(npp ~ SSlogis(evi_landsat, Asym, xmid, scal), data = npp_evi)))



npp_evi |> 
  ggplot(aes(x=evi_landsat, y = npp)) + 
  geom_point(aes(shape = elev_code, fill = sp_code, colour = sp_code)) +
  scale_colour_manual(values = colours_sp, name = "Species") +
  scale_shape_manual(values = shape_elev, name = "Elevation") +
  scale_fill_manual(values = colours_sp, name = "Species") + 
  theme_bw() +
  theme(
    panel.grid = element_blank(), 
    legend.background = element_blank(),
  ) +
  ylab(parse(text=label_npp)) +
  xlab(parse(text=label_landsat)) +
  geom_smooth(method = "lm", aes(fill = sp_code, colour = sp_code), se=FALSE, size =.7) +
  geom_smooth(method = "nls", 
              aes(), 
              formula = y~Asym/(1+exp(-(x-xmid)/scal)), 
              se =  FALSE, # this is important 
              method.args =list(start=init,
                                control=nls.control(maxiter=1000)), 
              colour = "black")
```

