---
title: "Soil features"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r pkg}
library(tidyverse)
library(sf)
library(terra)
```


```{r}
# read geoinfo to get site codes
geo <- st_read("data/geoinfo/geoinfo_dendro_adaptamed_pinus.shp", quiet=TRUE)
geo <- vect(geo)

geodf <- geo |> as.data.frame() |>
  rownames_to_column(var = "ID") |>
  mutate(ID = as.numeric(ID)) |> 
  dplyr::select(ID, site_code, sp_code, elev_code)
```

```{r}
soil_path <- "/Users/ajpelu/Downloads/Propiedades_Suelos_Andalucia"

hdr_files <- list.files(soil_path,
                        pattern = "*hdr.adf", full.names = TRUE, 
                        recursive = TRUE)

extractData <- function(f, shapefile_to_extract, remove_path, remove_pattern) { 
  
  r <- terra::rast(f)
  crs(r) <- "epsg:23030"
  
  # Get name and type 
  d <- data.frame(f = f) |> 
    mutate(raw_name = str_replace(f, pattern = paste0(remove_path, "/"), replacement = "")) |> 
    mutate(raw_name = str_replace(raw_name, pattern = "/hdr.adf$", "")) |> 
    separate(raw_name, into = c("type", "soil_var"), sep = "/") |> 
    dplyr::select(-f)
  
  if (crs(r) != crs(shapefile_to_extract)) {
    shapefile_to_extract <- terra::project(shapefile_to_extract, r)
  }
  
  out <- terra::extract(r, shapefile_to_extract) 
  names_out <- names(out)
  layer_name <- names_out[names_out != "ID"]
  
  result <- out |> 
    rename(value = !!layer_name) |> 
    mutate(value = ifelse(is.factor(value), as.numeric(value), value)) |> 
    mutate(layer = layer_name, 
           type = d$type, 
           soil_var = d$soil_var, 
           res = res(r)[1], 
           )
  
  return(result)     
  }


soil_features <- hdr_files |> purrr::map(~extractData(.x, shapefile_to_extract = geo, 
                                          remove_path = soil_path, 
                                          remove_pattern = "/hdr.adf")) |> 
  bind_rows() |> 
  inner_join(geodf)

write_csv(soil_features, "data/dendroadaptamed_soil_data.csv")
```



