---
title: "Forest stand structure "
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```


```{r}
library(tidyverse)
library(tinytable)
```


```{r}
rawdata <- readxl::read_excel("data/db_dendroadaptamed.xlsx", sheet = "tree_measurements") |> 
  dplyr::filter(stringr::str_detect(sp, "Pinus")) 

# |> 
#   dplyr::filter(sp != "Pinus cf. radiata")
# 


# pi*r^2 = BA
# dbh = 2r -> r = dbh/2
# pi*(dbh/2)^2 = BA
# pi*dbh^2/4 = BA
# dbh is in cm, so pass to m 
# BA = pi*dbh^2 / 40000

data <- rawdata |> 
  mutate(ba = (pi*(tree_dbh)^2)/40000) 

```



```{r}

# Functions to compute the Basal Area and Basal Area corrected and tree density and tree density corrected 
ba_plot<- function(x, ba_var, dist_var, ha = 10000, fc = 0.5){
  basum <- sum(x[, ba_var])
  radius_plot <- max(x[[dist_var]])
  ba <- (basum*ha)/(pi*radius_plot^2)
  bac <- (basum*ha)/((pi*radius_plot^2) + (0.5*radius_plot^2)/nrow(x))
  ntrees <- nrow(x)
  dentree <- (ntrees*ha)/(pi*radius_plot^2)
  dentreec <- (ntrees*ha)/((pi*radius_plot^2) + (0.5*radius_plot^2)/nrow(x))
  return(list(ba = ba, bac = bac, dentree = dentree, dentreec = dentreec))
}


## Mean Basal Area 
ba <- data |> 
  group_by(locality) |>
  group_modify(~{ 
    as.data.frame(
      ba_plot(.x, ba_var = "ba", dist_var="tree_distance_m", fc=0.5))
  }) 


## Mean Height, DBH (and sd)
mean_sd <- function(x) {
    tibble(
      mean = mean(x, na.rm = TRUE),
      sd = sd(x, na.rm = TRUE)
      )
}

h_dbh <- data |> reframe(across(tree_height:tree_dbh, mean_sd, .unpack = TRUE), .by = locality)
 
  

## Mean five tallest trees 
h5 <- data |> 
  group_by(locality) |> 
  slice_max(tree_height, n = 5) |> 
  ungroup() |> 
  group_by(locality) |> 
  summarise(h5 = mean(tree_height))
  

d <- ba |>  
  inner_join(h_dbh) |> 
  inner_join(h5)
```


```{r}
plots <- readxl::read_excel("data/db_dendroadaptamed.xlsx", sheet = "metadata_plots")
p <- plots |> dplyr::select(sp_main, locality_code, sp_elev, elev_category, site_code, elev_m, radio_m, tree_number, lai)

dd <- d |> inner_join(p, by=c("locality" = "locality_code")) |> 
  mutate(species = paste0("P. ", sp_main)) |> 
  dplyr::select(site_code, species, sp_elev, elev_category, elev_m, tree_number, radio_m, tree_dbh_mean, tree_dbh_sd, 
                tree_height_mean, tree_height_sd, tree_height5_mean = h5, bac, dentreec, lai)
  
write_csv(dd, "data/dendroadaptamed_stand_summary.csv")
```

```{r}
dd |> 
  ungroup() |> 
  arrange(species, elev_m) |> 
  dplyr::select(-species, -locality, -site_code, -elev_category) |> 
  tt() |> 
  group_tt(
    i = list(
      "halepensis" = 1,
      "pinaster" = 4, 
      "nigra" = 8, 
      "sylvestris" = 11
    ))
```





