---
title: "Soil features of the sampling sites"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```


## Introduction

```{r, message=FALSE}
library(tidyverse)
library(ggtern)
library(patchwork)
library(tinytable)
source("scripts/aux.R")
library(DT)
```


### Soil type 

- For each field site we show the soil types dominant and the inclussions.

```{r}
soil_type <- read_csv("data/dendroadaptamed_soil_lucdeme.csv")
```

```{r}
soil_type |> 
  dplyr::select(-site_code, -soil_type) |> 
  DT::datatable(options =
              list(
                autoWidth = TRUE,
                pageLength = 15), 
            filter = list(position = 'top', clear = FALSE)
            )
```


### Physico-Chemical features  

#### Texture 

```{r}
soil_fq <- read_csv("data/dendroadaptamed_soil_data.csv") |> 
  mutate(species = paste0("P. ", sp_code)) |>
  mutate(elev_code = case_when(
    elev_code == "low2" ~ "low-Dec", 
    TRUE ~ elev_code
  )) |> 
  mutate(elev_code = fct_relevel(elev_code, "low-Dec", "low", "medium", "high")) |> 
  mutate(sp_code = fct_relevel(sp_code, "halepensis","pinaster", "nigra", "sylvestris")) 
  
  
```


```{r}
custom_theme <- list(
  labs(yarrow = "Clay (%)",
       zarrow = "Silt (%)", 
       xarrow = "Sand (%)"),
  theme_bw(),
  ggplot2::xlab(""),
  ggplot2::ylab(""), 
  ggtern::zlab(""),
  theme_showarrows(),
  theme_showgrid(),
  scale_shape_manual(values = shape_elev, name = "Elevation"),
  scale_colour_manual(values = colours_Specie, labels = expression(italic("P. halepensis"), italic("P. pinaster"), italic("P. nigra"), italic("P. sylvestris")), name = "Species"),
  scale_fill_manual(values = colours_Specie, labels = expression(italic("P. halepensis"), italic("P. pinaster"), italic("P. nigra"), italic("P. sylvestris")),
    name = "Species"),
  # tern_limits(T=0.4, L = 0.8, R=0.5) 
  tern_limits(T=1, L = 1, R=1),
  theme(
    tern.axis.arrow.text = element_text(size = 14, face = "bold"), 
    tern.axis.arrow.text.T = element_text(vjust = -1), # clay
    tern.axis.arrow.text.L = element_text(vjust = -1), # sand
    tern.axis.arrow.text.R = element_text(vjust = 1), # silt
    tern.axis.text = element_text(size = 14),
    plot.title = element_text(face = "bold")
  )
)


gsup <- soil_fq |> 
  filter(type == "Textura Superficial") |> 
  dplyr::select(-res, -layer, -type) |> 
  pivot_wider(values_from = value, 
              names_from = soil_var)

plot_sup <- ggtern(data = gsup, 
       aes(x = arena_sup, y = arcilla_sup, z = limo_sup, 
           color = species, fill = species)) +
  geom_point(size = 5, aes(shape = elev_code), alpha = 0.8) +
  ggtitle("A", subtitle = "Soil texture surface (25-30 cm)") +
  custom_theme 
  

gsub <- soil_fq |> 
  filter(type == "Textura Subsuperficial") |> 
  dplyr::select(-res, -layer, -type) |> 
  pivot_wider(values_from = value, 
              names_from = soil_var)

plot_sub <- ggtern(data = gsub, 
                 aes(x = arena_sub, y = arcilla_sub, z = limo_sub, 
                    color = species, fill = species)) +
  geom_point(size = 5, aes(shape = elev_code), alpha = 0.8) +
  ggtitle("B", subtitle = "Soil texture subsurface (>30 cm)") +
  custom_theme
  
```

```{r}
#| fig.height: 6
#| fig.width: 12


library(gridExtra)
library(lemon)

common_legend <- lemon::g_legend(plot_sub + theme(legend.position = "bottom", 
                                                  legend.background = element_blank()))

combined_ggtern <- ggtern::grid.arrange(plot_sup + 
                                          theme(legend.position = "hidden",
                                                plot.margin = unit(c(t=0.4, r=-5, b=-.6, l=0), "cm")),
                                        plot_sub + 
                                          theme(legend.position = "hidden",
                                                plot.margin = unit(c(t=0.4, r=0, b=-.6, l=-5), "cm")),
                     common_legend,
                     # nrow = 1, 
                     # widths = c(2,2,0.5),
                     layout_matrix = matrix(c(1, 3, 2, 3), nrow = 2), 
                     heights = c(5,1))

combined_ggtern

ggsave(combined_ggtern, 
       filename = "output/soil_ternary.jpg",
       dpi = 500, 
       width = 12, height = 5)

```


```{r}
library(gtsummary)
library(openxlsx)

g <- gsup |> inner_join(gsub)

ternary_tab <- g |> 
  tbl_summary(by = species, 
              statistic = list(all_continuous() ~ "{mean}±{sd} ({min}-{max})"),
              include = c(arcilla_sup, arena_sup, limo_sup, 
                          arcilla_sub, arena_sub, limo_sub))

ternary_tab
```

```{r}
ternary_tab |> as_tibble() |> openxlsx::write.xlsx("output/tables/soil_ternary_means.xlsx")
```

##### Comparison Ternary composition

```{r}
# anova(aov(arcilla_sub ~ species, data = g)) |> broom::tidy()

anova_ternary <- g |> 
  dplyr::select(-ID) |> 
  select_if(is.numeric) |> 
  map(~ broom::tidy(anova(aov(. ~ g$species)))) |> 
  bind_rows(.id = "var") 

anova_ternary |> openxlsx::write.xlsx("output/tables/soil_ternary_anova.xlsx")

anova_ternary |> DT::datatable() |> 
  formatRound(columns = c(4:7), digits=3)
```



### Other parameters

```{r}
fq_notextura <- soil_fq |> 
  filter(soil_var %in% c("cc_sup", "cc_sub",
             "pmp_sup", "pmp_sub", 
             "retencion_all",
             "da_sup", "da_sub", 
             "ph_sup", "ph_sub",
             "mo_sup", "mo_sub",
             "ks_sup", "ks_sub", 
             "Conductividad Saturada Aparente Superficial",
             "Conductividad Saturada Aparente Subsuperficial", 
             "Contenido de Agua Residual Superficial", 
             "Contenido de Agua Residual Subsuperficial",
             "Contenido de Agua Saturación Superficial",
             "Contenido de Agua Saturación Subsuperficial"
             ))


d <- fq_notextura |> 
  dplyr::select(sp_code, elev_code, value, soil_var) |> 
  pivot_wider(values_from = value,
              names_from = soil_var) |>
  arrange(
    factor(sp_code, levels = c("halepensis", "pinaster", "nigra", "sylvestris")), 
    factor(elev_code, levels = c("low2", "low", "medium", "high"))) |> 
  relocate(sp_code, elev_code,
           cc_sup, cc_sub,
           retencion_all,
             pmp_sup, pmp_sub, 
             da_sup, da_sub, 
             ph_sup, ph_sub,
             mo_sup, mo_sub,
             ks_sup, ks_sub, 
             `Conductividad Saturada Aparente Superficial`,
             `Conductividad Saturada Aparente Subsuperficial`, 
             `Contenido de Agua Residual Superficial`, 
             `Contenido de Agua Residual Subsuperficial`,
             `Contenido de Agua Saturación Superficial`,
             `Contenido de Agua Saturación Subsuperficial`) 
  

           
mitabla <- d |> 
  dplyr::select(-sp_code) |> 
  tt() |> 
  group_tt(
    i = list(
      "halepensis" = 1,
      "pinaster" = 4, 
      "nigra" = 8, 
      "sylvestris" = 11
    ),
    j = list(
      "Capacidad Campo (cm3/cm3)" = 2:3,
      "Retención de agua (mm)" = 4,
      "Punto de Marchitez Permanente (cm3/cm3)" = 5:6,
      "Densidad aparente (gr/cm3)" = 7:8, 
      "pH" = 9:10,
      "M. Orgánica (%)" = 11:12,
      "Conductividad Hidráulica Saturada (cm/día)" = 13:14, # ks 
      "Conductividad Saturada Aparente (cm/día)" = 15:16, 
      "Contenido de Agua Residual (cm3/cm3)" = 17:18, 
      "Contenido de Agua Saturacion (cm3/cm3)" = 19:20
      ) 
  ) 


mitabla
``` 

```{r}
dicc_fq <- read_csv("data/raw/soil/dicc_fq.csv")

f <- fq_notextura |> 
  inner_join(dicc_fq) 
  
par_sup <- f |> 
  filter(soil_var != "retencion_all") |> 
  filter(deepth == "sup") |> 
  ggplot(aes(x = factor(elev_code, levels = c("low2", "low", "medium", "high")),
                        y = value, group = sp_code, colour = sp_code, fill = sp_code)) +
  geom_point(aes(color = sp_code), size = 2, shape = 21) +
  geom_line() +
  facet_wrap(~soil_var_groupped, scales = "free") +
  scale_colour_manual(values = colours_sp, name = "Pine species") + 
  scale_fill_manual(values = colours_sp, name = "Pine species") +
  theme_bw() +
  theme(
    legend.position = "bottom",
    panel.grid = element_blank()
  ) +
  xlab("") + ylab("") +
  ggtitle("Superficial")

par_sup
```


```{r}
ggsave(par_sup, 
       filename = "output/soil_fq_superficial.jpg",
       width = 10, height = 10)
```


```{r}
par_sub <- f |> 
  filter(soil_var != "retencion_all") |> 
  filter(deepth == "sub") |> 
  ggplot(aes(x = factor(elev_code, levels = c("low2", "low", "medium", "high")),
                        y = value, group = sp_code, colour = sp_code, fill = sp_code)) +
  geom_point(aes(color = sp_code), size = 2, shape = 21) +
  geom_line() +
  facet_wrap(~soil_var_groupped, scales = "free") +
  scale_colour_manual(values = colours_sp, name = "Pine species") + 
  scale_fill_manual(values = colours_sp, name = "Pine species") +
  theme_bw() +
  theme(
    legend.position = "bottom",
    panel.grid = element_blank()
  ) +
  xlab("") + ylab("") +
  ggtitle("Subsuperficial")

par_sub 
```


```{r}
ggsave(par_sub, 
       filename = "output/soil_fq_subsuperficial.jpg",
       width = 10, height = 10)
```
 
